language: node_js
node_js:
  - "7"
install:
  - npm install
env:
  - export __OW_API_HOST=openwhisk.ng.bluemix.net __OW_API_KEY=5c5820ff-1e7a-44ae-b38a-7b70b215cb8c:AqtqbYpavejPt4fjM5vlzSqpSmdU1QZ3I98hqEYykkbwcybPw4t4IcWpedVOzzFM
script:
  - eslint .
  - npm run coverage
  - node ./node_modules/.bin/istanbul check-coverage --statements 90 --branches 90 --lines 90 --functions 90